repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8  # Use the latest tag from https://github.com/astral-sh/ruff-pre-commit/tags
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
