apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: shortner-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "ChangeMe!"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        - name: GF_DATASOURCES_DEFAULT
          value: "prometheus"
        volumeMounts:
        - name: grafana-ds
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-ds
        configMap:
          name: grafana-ds