apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: shortner-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      containers:
      - name: prometheus
        image: prom/prometheus:v2.50.0
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.enable-lifecycle"
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
