apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  namespace: shortner-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
      annotations:
        sidecar.jaegertracing.io/inject: "true"
    spec:
      containers:
      - name: ui
        image: your-registry/ui-service:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
