"""added id counter table

Revision ID: 04f4218549fe
Revises: dcd40f5f8734
Create Date: 2025-08-14 20:08:09.153827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '04f4218549fe'
down_revision: Union[str, Sequence[str], None] = 'dcd40f5f8734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idcounter',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idcounter_key'), 'idcounter', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idcounter_key'), table_name='idcounter')
    op.drop_table('idcounter')
    # ### end Alembic commands ###
