"""added url click counts table

Revision ID: edd0d3a6a4ba
Revises: 70c933bac474
Create Date: 2025-10-18 10:35:11.261518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'edd0d3a6a4ba'
down_revision: Union[str, Sequence[str], None] = '70c933bac474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlclickcount',
    sa.Column('short_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('counts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['short_url'], ['url.short_url'], ),
    sa.PrimaryKeyConstraint('short_url', 'country_code')
    )
    op.alter_column('idcounter', 'next_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idcounter', 'next_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('urlclickcount')
    # ### end Alembic commands ###
