services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis-users.acl:/usr/local/etc/redis/users.acl:ro
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui-service
      - shortner-service
    restart: unless-stopped

  ui-service:
    build:
      context: ../../ui-service
      dockerfile: Dockerfile
    container_name: ui-service
    expose:
      - "8001"
    environment:
      - PORT=8001
      - CONFIG_FILE_PATH=/app/config.yaml
    volumes:
      - ./ui_config.yaml:/app/config.yaml
    depends_on:
      - shortner-service
    restart: unless-stopped

  shortner-service:
    build:
      context: ../../shortner-service
      dockerfile: Dockerfile
    container_name: shortner-service
    expose:
      - "8000"
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml
    volumes:
      - ./shortner_config.yaml:/app/config.yaml
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=shortner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortner
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
