apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds
  namespace: shortner-monitoring
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.shortner-monitoring.svc.cluster.local:9090
        isDefault: true