environment: local
secret_key: random-string

postgres_host: localhost
postgres_port: 5432
postgres_db: shortner
postgres_user: shortner
postgres_password: password

jwt_secret: random-string-2
jwt_algorithm: HS256
jwt_expire_duration_minutes: 30

id_counter_key: default
id_counter_batch_size: 1000
hash_id_counter_secret: id-secret
base_url: http://localhost:8000/
redis_host: localhost
redis_user: admin
redis_password: password
click_analytics_topic: clicks-stream
click_analytics_consumer_group: postgres-writers
click_analytics_batch_count: 100