environment: local
secret_key: random-string

postgres_host: localhost
postgres_port: 5432
postgres_db: shortner
postgres_user: shortner
postgres_password: password

jwt_secret: random-string-2
jwt_algorithm: HS256
jwt_expire_duration_minutes: 30