apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: shortner-monitoring
spec:
  type: ClusterIP
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: grpc
    port: 14250
    targetPort: 14250
  - name: zipkin
    port: 9411
    targetPort: 9411
  selector:
    app: jaeger